services:
  app:
    container_name: git-webhook-deployer
    env_file:
      - .env
    build:
      context: .
      target: ${APP_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'